# Generated by Django 4.1.7 on 2023-10-12 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.SmallIntegerField(verbose_name='grade')),
            ],
            options={
                'verbose_name': 'grade',
                'verbose_name_plural': 'grades',
            },
        ),
        migrations.CreateModel(
            name='StudentsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, verbose_name='fullname')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='student.grade', verbose_name='grade')),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
            },
        ),
        migrations.CreateModel(
            name='PresenceOrAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('absent', models.ManyToManyField(related_name='absents', to='student.studentslist')),
                ('present', models.ManyToManyField(related_name='presents', to='student.studentslist')),
            ],
        ),
    ]
